version: '3'

services:
  postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    volumes:
      - /home/mauricio/Desktop/projetos/volume/:/var/lib/postgresql/data
    networks:
      - postgres-compose-network
      
  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports:
      - "5050:80"
    depends_on:
      - postgres-compose
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge
